// This file is generated by `cargo run --manifest-path src-tauri/Cargo.toml --bin generate_desktop_contracts`.
// Do not edit it by hand.

export type StatusCategory = "action" | "info" | "debug" | "error" | "completion" | "warning";

export type FileOperation = "create" | "overwrite" | "replace" | "remove" | "undo";

export type OutputPreview = { content: string, totalLines: number, headDisplayLines: string | null, tailDisplayLines: string | null, fullOutputPath: string | null, };

export type ToolCallDetail = { "kind": "file_read", path: string, startLine: number | null, endLine: number | null, } | { "kind": "file_update", path: string, operation: FileOperation, } | { "kind": "shell", command: string, cwd: string | null, description: string | null, } | { "kind": "search", pattern: string, path: string | null, glob: string | null, fileType: string | null, } | { "kind": "codebase_search", queries: Array<string>, } | { "kind": "fetch", url: string, } | { "kind": "followup", question: string, } | { "kind": "plan", planName: string, } | { "kind": "skill", name: string, } | { "kind": "task", agentId: string, } | { "kind": "todo_write", count: number, } | { "kind": "todo_read" } | { "kind": "unknown", name: string, };

export type ToolResultDetail = { "kind": "file_diff", path: string, patch: string, } | { "kind": "shell_output", command: string, shell: string, exitCode: number | null, description: string | null, stdout: OutputPreview | null, stderr: OutputPreview | null, } | { "kind": "text", text: string, };

export type FollowupKind = "text" | "single" | "multi";

export type FollowupOption = { id: string, label: string, };

export type FollowupRequest = { followupId: string, workspacePath: string, conversationId: string, requestId: string, kind: FollowupKind, question: string, options: Array<FollowupOption> | null, };

export type FollowupResponse = { followupId: string, cancelled: boolean, text: string | null, selectedOptionIds: Array<string> | null, };

export type SessionMessage = { "kind": "user", id: string, requestId: string, text: string, } | { "kind": "context_compacted", id: string, requestId: string, text: string, } | { "kind": "assistant", id: string, requestId: string, text: string, } | { "kind": "reasoning", id: string, requestId: string, text: string, } | { "kind": "status", id: string, requestId: string, title: string, subtitle: string | null, category: StatusCategory, } | { "kind": "status_output", id: string, requestId: string, text: string, } | { "kind": "tool_start", id: string, requestId: string, name: string, callId: string | null, detail: ToolCallDetail, } | { "kind": "tool_end", id: string, requestId: string, name: string, callId: string | null, summary: string | null, isError: boolean, detail: ToolResultDetail | null, } | { "kind": "error", id: string, requestId: string, message: string, };

export type SessionTodoStatus = "pending" | "in_progress" | "completed" | "cancelled";

export type SessionTodo = { id: string, content: string, status: SessionTodoStatus, };

export type ConversationSessionSummary = { conversationId: string, title: string, updatedAt: string | null, isDraft: boolean, isRunning: boolean, hasPendingFollowup: boolean, };

export type ChatBinding = { workspacePath: string, conversationId: string, };

export type ConversationViewSnapshot = { workspacePath: string, conversationId: string, messages: Array<SessionMessage>, activeRequestIds: Array<string>, todos: Array<SessionTodo>, followup: FollowupRequest | null, };

export type WorkspaceKind = "project" | "managed_chat";

export type WorkspaceSession = { kind: WorkspaceKind, workspacePath: string, workspaceName: string, configured: boolean, configurationError: string | null, selectedConversationId: string | null, conversations: Array<ConversationSessionSummary>, };

export type SavedWorkspaceSummary = { id: string, name: string, updatedAt: bigint, };

export type SavedWorkspaceDetail = { id: string, name: string, layoutJson: string, updatedAt: bigint, };

export type SessionSnapshot = { activeWorkspacePath: string | null, activeConversationId: string | null, visibleMessages: Array<SessionMessage>, visibleActiveRequestIds: Array<string>, visibleTodos: Array<SessionTodo>, visibleFollowup: FollowupRequest | null, conversationViews: Array<ConversationViewSnapshot>, uiError: string | null, workspaces: Array<WorkspaceSession>, savedWorkspaces: Array<SavedWorkspaceSummary>, };

export type PromptModelOption = { providerId: string, providerName: string, modelId: string, modelName: string | null, contextLength: bigint | null, supportsReasoning: boolean, reasoningEfforts: Array<string>, };

export type PromptSettings = { availableModels: Array<PromptModelOption>, selectedProviderId: string | null, selectedModelId: string | null, selectedReasoningEffort: string | null, };

export type UpdatePromptSettingsInput = { workspacePath: string | null, providerId: string, modelId: string, reasoningEffort: string | null, };

export type ProviderAuthMethodKind = "api_key" | "o_auth_device" | "o_auth_code" | "google_adc" | "codex_device";

export type ProviderAuthMethod = { kind: ProviderAuthMethodKind, label: string, };

export type ProviderSummary = { id: string, name: string, configured: boolean, authMethods: Array<ProviderAuthMethod>, };

export type ProviderUrlParam = { name: string, value: string | null, options: Array<string> | null, };

export type ProviderUrlParamValue = { name: string, value: string, };

export type ProviderAuthSessionKind = "api_key" | "device_code" | "o_auth_code";

export type ProviderAuthSession = { kind: ProviderAuthSessionKind, authSessionId: string, requiresApiKey: boolean, apiKeyHint: string | null, urlParameters: Array<ProviderUrlParam>, verificationUri: string | null, verificationUriComplete: string | null, userCode: string | null, expiresInSeconds: bigint | null, authorizationUrl: string | null, };

export type StartProviderAuthInput = { workspacePath: string | null, providerId: string, authMethod: ProviderAuthMethodKind, };

export type CompleteProviderAuthInput = { authSessionId: string, apiKey: string | null, authorizationCode: string | null, urlParameters: Array<ProviderUrlParamValue>, };

export type RemoveProviderInput = { workspacePath: string | null, providerId: string, };

export type SendPromptInput = { workspacePath: string, prompt: string, conversationId: string | null, agentId: string | null, };

export type ChatHandoffTarget = "local" | "worktree";

export type HandoffChatInput = { sourceWorkspacePath: string, conversationId: string | null, target: ChatHandoffTarget, branchName: string | null, };

export type RuntimeStatus = { workspacePath: string | null, workspaceName: string | null, gitRepoName: string | null, gitBranchName: string | null, gitBranches: Array<string>, gitWorkspaceKind: GitWorkspaceKind | null, gitMainWorkspacePath: string | null, availableOpenTargets: Array<string>, configured: boolean, configurationError: string | null, };

export type GitWorkspaceKind = "local" | "worktree";

export type CloneRepositoryInput = { repositoryUrl: string, parentDirectory: string, directoryName: string, };

export type QuickStartVisibility = "public" | "private";

export type QuickStartProjectInput = { projectName: string, parentDirectory: string, visibility: QuickStartVisibility, };

export type CheckoutGitBranchInput = { workspacePath: string, branchName: string, };

export type CreateGitBranchInput = { workspacePath: string, branchName: string, };

export type CommitGitChangesInput = { workspacePath: string, message: string, };

export type CreateSavedWorkspaceInput = { chats: Array<ChatBinding>, layoutJson: string, };

export type UpdateSavedWorkspaceLayoutInput = { workspaceId: string, layoutJson: string, };

export type SaveConversationLayoutInput = { conversationId: string, layoutJson: string, };

export type TerminalOpenInput = { terminalId: string, workspacePath: string, cols: number, rows: number, };

export type TerminalWriteInput = { terminalId: string, data: string, };

export type TerminalResizeInput = { terminalId: string, cols: number, rows: number, };

export type TerminalCloseInput = { terminalId: string, };

export type TerminalSession = { terminalId: string, workspacePath: string, shell: string, cols: number, rows: number, };

export type TerminalOutputEvent = { terminalId: string, data: string, };

export type TerminalExitEvent = { terminalId: string, exitCode: number | null, signal: string | null, };

export type TerminalErrorEvent = { terminalId: string, message: string, };
