// This file is generated by `cargo run --manifest-path src-tauri/Cargo.toml --bin generate_desktop_contracts`.
// Do not edit it by hand.

export type StatusCategory = "action" | "info" | "debug" | "error" | "completion" | "warning";

export type FollowupKind = "text" | "single" | "multi";

export type FollowupOption = { id: string, label: string, };

export type FollowupRequest = { followupId: string, workspacePath: string, conversationId: string, requestId: string, kind: FollowupKind, question: string, options: Array<FollowupOption> | null, };

export type FollowupResponse = { followupId: string, cancelled: boolean, text: string | null, selectedOptionIds: Array<string> | null, };

export type SessionMessage = { "kind": "user", id: string, requestId: string, text: string, } | { "kind": "assistant", id: string, requestId: string, text: string, } | { "kind": "reasoning", id: string, requestId: string, text: string, } | { "kind": "status", id: string, requestId: string, title: string, subtitle: string | null, category: StatusCategory, } | { "kind": "status_output", id: string, requestId: string, text: string, } | { "kind": "tool_start", id: string, requestId: string, name: string, } | { "kind": "tool_end", id: string, requestId: string, name: string, summary: string | null, isError: boolean, } | { "kind": "error", id: string, requestId: string, message: string, };

export type ConversationSessionSummary = { conversationId: string, title: string, updatedAt: string | null, isDraft: boolean, isRunning: boolean, hasPendingFollowup: boolean, };

export type WorkspaceSession = { workspacePath: string, workspaceName: string, configured: boolean, configurationError: string | null, selectedConversationId: string | null, conversations: Array<ConversationSessionSummary>, };

export type SessionSnapshot = { activeWorkspacePath: string | null, activeConversationId: string | null, visibleMessages: Array<SessionMessage>, visibleFollowup: FollowupRequest | null, uiError: string | null, workspaces: Array<WorkspaceSession>, };

export type SendPromptInput = { workspacePath: string, prompt: string, conversationId: string | null, };
